
self_path: 1-training_data/segment_config.yaml # for programmatic updating

# Project definitions
video_path: null
segmentation_type: 2d

# Preprocessing
preprocessing_config: 1-segmentation/preprocessing_config.yaml

# Segmentation
segmentation_params:
  stardist_model_name: lukas

# Postprocessing
postprocessing_params:
  upper_length_threshold: 12
  lower_length_threshold: 3
  to_remove_border: true
  border_width_to_remove: 50

# Output
output:
  folder: 1-segmentation # Only used for initial writing
  masks: 1-segmentation/masks.btf
  metadata: 1-segmentation/metadata.pickle

# Printing
verbose: 1
DEBUG: false
