---
# Project definitions
video_path: null
segmentation_type: 2d

# Preprocessing
preprocessing_config: 1-segmentation/preprocessing_config.yaml

# Segmentation
segmentation_params:
  stardist_model_name: lukas

# Postprocessing
postprocessing_params:
  upper_length_threshold: 12
  lower_length_threshold: 3
  to_remove_border: true
  border_width_to_remove: 100

# Output
output_params:
  output_folder: 1-segmentation

# Printing
verbose: 1
DEBUG: false
