
self_path: 1-segmentation/segment_config.yaml # for programmatic updating

# Project definitions
video_path: null
segmentation_type: 3d

# External preprocessing: bounding boxes
bbox_fname: 1-segmentation/bounding_boxes.pickle

# Segmentation
segmentation_params:
  stardist_model_name: charlie_3d
  zero_out_borders: true

# Postprocessing
postprocessing_params:
  upper_length_threshold: 12
  lower_length_threshold: 3
  to_remove_border: false
  border_width_to_remove: 0
  to_remove_dim_slices: true
  min_separation: 6

# Output
output_folder: 1-segmentation # Only used for initial writing
output_masks: 1-segmentation/masks.btf
output_metadata: 1-segmentation/metadata.pickle

# Printing
verbose: 1
DEBUG: false
