# Example from: https://hackmd.io/@bluegenes/BJPrrj7WB
# cluster_config.yml - cluster configuration
__default__:
    partition: basic
    time: 04:00:00
    nodes: 1
    cpus_per_task: 4
    mem: 64G
    output: log_snakemake_step-%j.out

preprocessing:
    time: 18:00:00
    partition: himem
    mem: 600G

segmentation:
    time: 18:00:00
    mem: 600G
    cpus_per_task: 32
    partition: himem

match_frame_pairs:
    partition: gpu
    time: 08:00:00

build_frame_objects:
    cpus_per_task: 16

postprocess_matches_to_tracklets:
    partition: gpu
    cpus_per_task: 1

tracking:
    partition: gpu

combine_tracking_and_tracklets:
    time: 12:00:00

extract_full_traces:
    time: 02:00:00