
# Global requirement
project_dir: "/scratch/zimmer/Charles/dlc_stacks/worm3-2021_09_29"
#project_path: "/scratch/zimmer/Charles/dlc_stacks/worm3-2021_09_29/project_config.yaml"
code_path: "/scratch/zimmer/Charles/github_repos/dlc_for_wbfm/DLC_for_WBFM/scripts"

# Step 0: preprocessing
#... for now, do manually
output_0:
  - 1-segmentation/bounding_boxes.pickle # Optional

# Step 1: segmentation
# This is the beginning, with no required input except raw data
# NOTE: raw data is outside the project, and thus is not in this format
input_1:
  - 1-segmentation/bounding_boxes.pickle # Optional
output_1_dir:
  - 1-segmentation/masks.zarr
output_1:
  - 1-segmentation/metadata.pickle

# Step 2: tracklets
input_2a_dir:
  - 1-segmentation/masks.zarr
input_2a:
  - 1-segmentation/metadata.pickle
output_2a:
  - 2-tracklets/raw/frame_dat.pickle
  - 2-tracklets/raw/match_dat.pickle

input_2b:
  - 2-tracklets/raw/frame_dat.pickle
  - 2-tracklets/raw/match_dat.pickle
output_2b:
  - 2-tracklets/all_tracklets.h5
  - 2-tracklets/raw/clust_df_dat.pickle

input_2c:
  - 2-tracklets/all_tracklets.h5
output_2c_dir:
  - 2-tracklets/reindexed_masks.zarr

input_2d:
  - 2-tracklets/raw/clust_df_dat.pickle
output_2d:
  - 2-tracklets/training_data_tracks.h5
  - 2-tracklets/reindexed_metadata.pickle

# Step 3: dlc... for now, just combine all steps
# NOTE: should be done on cluster
# However, the .avi videos should be created off the cluster...
input_3_dlc:
  - 3-tracking/ONCLUSTER.FAKE
  - 2-tracklets/training_data_tracks.h5
  - 2-tracklets/reindexed_masks.zarr
output_3_dlc:
  - 3-tracking/full_3d_tracks.h5


# Step 3: Alternate: leifer style
input_3a:
  - 1-segmentation/metadata.pickle
  - 2-tracklets/reindexed_metadata.pickle
output_3a:
  - 3-tracking/postprocessing/leifer_tracks.h5

input_3b:
  - 3-tracking/postprocessing/leifer_tracks.h5
  - 2-tracklets/all_tracklets.h5
output_3b:
  - 3-tracking/postprocessing/combined_3d_tracks.h5

# Step 4: final traces
input_4a:
  - 3-tracking/postprocessing/combined_3d_tracks.h5
  - 1-segmentation/metadata.pickle
output_4a:
  - 4-traces/all_matches.pickle

input_4b:
  - 4-traces/all_matches.pickle
input_4b_dir:
  - 1-segmentation/masks.zarr
output_4b_dir:
  - 4-traces/reindexed_masks.zarr

# Note: also needs raw data
input_4c_dir:
  - 4-traces/reindexed_masks.zarr
output_4c:
  - 4-traces/red_traces.h5
  - 4-traces/green_traces.h5
