# Example from: https://hackmd.io/@bluegenes/BJPrrj7WB
# cluster_config.yml - cluster configuration
__default__:
    partition: basic
    time: 18:00:00
    nodes: 1
    cpus_per_task: 4
    mem: 32G
    disk_mb: 8000
    mem_mb: 8000
    output: log_snakemake_step-%j.out

# Note: himem is not actually needed at the moment, but is usually more free for large jobs
preprocessing:
    cpus_per_task: 42

# Note: himem is not actually needed at the moment, but is usually more free for large jobs
segmentation:
    mem: 600G
    cpus_per_task: 42
    partition: himem

match_frame_pairs:
    partition: gpu
    gpus_per_node: 1

build_frame_objects:
    cpus_per_task: 42

postprocess_matches_to_tracklets:
    partition: gpu
    cpus_per_task: 1

tracking:
    partition: gpu
    gpus_per_node: 1
