# Example from: https://hackmd.io/@bluegenes/BJPrrj7WB
# cluster_config.yml - cluster configuration
__default__:
    partition: basic
    time: 0-2:00:00
    nodes: 1
    cpus_per_task: 4
    mem: 64G
    disk_mb: 8000
    mem_mb: 8000
    output: log_snakemake_step-%j.out

# Note: may need to push over to himem if the cluster is busy
preprocessing:
    time: 0-18:00:00
    mem: 128G
    cpus_per_task: 64

segmentation:
    time: 0-18:00:00
    mem: 256G
    cpus_per_task: 68

match_frame_pairs:
    partition: gpu
    gpus_per_node: 1
    time: 0-12:00:00
    mem: 128G

build_frame_objects:
    time: 0-6:00:00
    cpus_per_task: 42

postprocess_matches_to_tracklets:
    partition: gpu
    cpus_per_task: 1
    time: 0-2:00:00

tracking:
    partition: gpu
    gpus_per_node: 1
    cpus_per_task: 16
