# Example from: https://hackmd.io/@bluegenes/BJPrrj7WB
# cluster_config.yml - cluster configuration
# For the actual available resources, see the cluster documentation:
# https://lisc.univie.ac.at/wiki/content/working_environment/services/computational_resources

__default__:
    partition: basic
    time: 0-4:00:00
    nodes: 1
    cpus_per_task: 16
    mem: 64G
    disk_mb: 8000
    mem_mb: 8000
    output: log_snakemake_step-%j.out
    gres: # Should be empty

# Note: may need to push over to himem if the cluster is busy
preprocessing:
    time: 1-12:00:00
    mem: 120G
    cpus_per_task: 40

segmentation:
    time: 1-12:00:00
    mem: 256G
    cpus_per_task: 40

match_frame_pairs:
    partition: basic,gpu
    gpus_per_node: 1
    time: 0-12:00:00
    mem: 128G
    gres: shard:32

build_frame_objects:
    time: 0-12:00:00
    cpus_per_task: 20

postprocess_matches_to_tracklets:
    partition: basic,gpu
    cpus_per_task: 1
    time: 0-2:00:00
    gres: shard:32

combine_tracking_and_tracklets:
    time: 0-18:00:00
    cpus_per_task: 20

tracking:
    partition: basic,gpu
    gpus_per_node: 1
    cpus_per_task: 16
    gres: shard:32

# Behavior
subtract_background:
    time: 0-08:00:00
    mem: 4G
    cpus_per_task: 8

dlc_analyze_videos:
    time: 0-08:00:00
    partition: basic,gpu
    mem: 0
    cpus_per_task: 24
    gres: shard:32

create_centerline:
    time: 0-08:00:00
    mem: 8G
    cpus_per_task: 4

normalize_img:
    time: 0-08:00:00
    mem: 4G
    cpus_per_task: 8

worm_unet:
    time: 0-08:00:00
    partition: basic,gpu
    mem: 0
    cpus_per_task: 24
    gres: shard:32

coil_unet:
    time: 0-08:00:00
    partition: basic,gpu
    mem: 0
    cpus_per_task: 24
    gres: shard:32

binarize:
    time: 0-08:00:00
    cpus_per_task: 8
